# -*- coding: utf-8 -*-
"""Multi Modal Product Recommendation Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kt3QCqjxVKgsXuuWMzglvvQ4kjd7sB98

# Start
"""

import nltk
import string
import pandas as pd
from nltk import word_tokenize
from tqdm.notebook import tqdm
from nltk.corpus import stopwords
from transformers import pipeline
from nltk.stem import WordNetLemmatizer
from transformers import AutoTokenizer, AutoModel

nltk.download('wordnet')
nltk.download('punkt')
nltk.download('stopwords')

from google.colab import drive

drive.mount('/content/drive')

"""# Load"""

file_path = '/content/drive/MyDrive/Datasets/Raw/amazon_product_reviews.csv'
df = pd.read_csv(file_path)

df['Score'] = df['Score'] - 1

print('Unique labels: ', sorted(df['Score'].unique()))
df.head(3)

"""# Calculate Sentiment"""

TWITTER_SENTI_MODEL_PATH = 'cardiffnlp/twitter-roberta-base-sentiment-latest'
BASE_ROBERTA_MODEL_PATH = 'FacebookAI/roberta-base'

"""## Pre Trained Roberta Model"""

sentiment_labeling_automatic = pipeline("sentiment-analysis", model=TWITTER_SENTI_MODEL_PATH, tokenizer=TWITTER_SENTI_MODEL_PATH)

df = df.head(1000)

scores = []

for text in tqdm(df['Text']):
    try:
        scores.append(sentiment_labeling_automatic(text))
    except:
        scores.append(None)

df['Roberta_Sentiment'] = scores

display(df['Roberta_Sentiment'])

df.to_csv('/content/drive/MyDrive/Datasets/Processed/amazon_product_reviews_sentiment.csv', index=False)

"""## Manual Senti Assignment"""

df['Label'] = 'positive'
label = []
for score in tqdm(df['Score'].astype(int)):
    if score >= 0 and score < 2:
        label.append('negative')
    elif score == 2:
        label.append('neutral')
    elif score > 2 and score <= 4:
        label.append('positive')

df['Label'] = label

"""save dataframe into csv"""

# tqdm(df.rename(columns={'Senti-Label':'Label'}, inplace=True))
display(df.head(2))

"""*Preprocess df['Text']*"""

stop_words = set(stopwords.words('english')) - {'not', 'no', 'nor'}
lemmatizer = WordNetLemmatizer()
transtable = str.maketrans('', '', string.punctuation)

def preprocess(text):
    text = text.lower().strip()
    text = ' '.join(text.split())
    text = text.translate(transtable)

    words = text.split()

    words = [
        lemmatizer.lemmatize(w)
        for w in words
        if w not in stop_words
    ]

    return " ".join(words)

df["Text"] = [preprocess(t) for t in tqdm(df["Text"])]

display(df.loc[:, ['Score', 'Label', 'Text']].head(50))
df.loc[:, ['Score', 'Label', 'Text']].to_csv('/content/drive/MyDrive/Datasets/Processed/amazon_product_reviews_sentiment_preprocessed.csv', index=False)

"""save this dataframe to a csv file"""

df.to_csv('/content/drive/MyDrive/Datasets/Processed/amazon_product_reviews_sentiment.csv', index=False)

"""# Real Training"""

file_path = '/content/drive/MyDrive/Datasets/Processed/amazon_product_reviews_sentiment_preprocessed.csv'
df = pd.read_csv(file_path)

"""Setup training model."""

model_name = 'google-bert/bert-base-uncased'
model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

texts = df['Text'].tolist()
labels = df['Label'].tolist()

tokens = tokenizer(texts, max_length=512, truncation=True, padding=True, return_tensors='pt')

!pip install torch

"""# Training Code"""

!pip install -U transformers accelerate datasets

import transformers
print(transformers.__version__)

import os
import pickle
import pandas as pd
import torch

from google.colab import files
from dotenv import load_dotenv
from torch.utils.data import random_split
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
    TrainerCallback
)

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# -----------------------------
# Load Data
# -----------------------------

def load_data(path: str) -> pd.DataFrame:
    return pd.read_csv(path)

# -----------------------------
# Torch Dataset
# -----------------------------

class TorchReviewDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):

        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }

        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# -----------------------------
# Metrics
# -----------------------------

def compute_metrics(eval_pred):

    logits, labels = eval_pred
    predictions = logits.argmax(axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

# -----------------------------
# Pickle Checkpoint Callback
# -----------------------------

class PickleCheckpointCallback(TrainerCallback):

    def on_save(self, args, state, control, **kwargs):

        model = kwargs["model"]
        optimizer = kwargs["optimizer"]
        scheduler = kwargs["lr_scheduler"]

        checkpoint_dir = os.path.join(
            args.output_dir,
            f"checkpoint-{state.global_step}"
        )

        pickle_path = os.path.join(checkpoint_dir, "model_state.pkl")

        checkpoint_data = {
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "scheduler_state_dict": scheduler.state_dict(),
            "epoch": state.epoch,
            "global_step": state.global_step
        }

        with open(pickle_path, "wb") as f:
            pickle.dump(checkpoint_data, f)

        print(f"Saved pickle checkpoint → {pickle_path}")

# -----------------------------
# Main Training Script
# -----------------------------

load_dotenv()

# DATASET_PATH = "/content/drive/MyDrive/Datasets/Processed/amazon_product_reviews_sentiment_preprocessed.csv"
# OUTPUT_DIR = "/content/drive/MyDrive/models/trained/multimodal_product_review_analyzer"

DATASET_PATH = "/content/drive/MyDrive/Datasets/Processed/amazon_product_reviews_sentiment_preprocessed.csv"
MODEL_NAME = "google-bert/bert-base-uncased"
OUTPUT_DIR = "/content/trained_model/"

# Load dataset
df = load_data(DATASET_PATH)

# limit dataset (optional)
df = df.head(5000)

texts = df["Text"].tolist()
labels = df["Label"].tolist()

# label encoding
labels_map = {
    "negative": 0,
    "neutral": 1,
    "positive": 2
}

labels = [labels_map[label] for label in labels]

# -----------------------------
# Tokenizer + Model
# -----------------------------

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3
)

# -----------------------------
# Tokenization
# -----------------------------

encodings = tokenizer(
    texts,
    truncation=True,
    max_length=512
)


dataset = TorchReviewDataset(encodings, labels)

# -----------------------------
# Train / Validation Split
# -----------------------------

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)

# -----------------------------
# Training Arguments
# -----------------------------

training_args = TrainingArguments(

    output_dir=OUTPUT_DIR,

    learning_rate=2e-5,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    num_train_epochs=15,

    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="f1",

    logging_dir="./logs",

    report_to="none"
)

# -----------------------------
# Data Collator
# -----------------------------

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# -----------------------------
# Trainer
# -----------------------------

trainer = Trainer(

    model=model,
    args=training_args,

    train_dataset=train_dataset,
    eval_dataset=val_dataset,

    data_collator=data_collator,

    compute_metrics=compute_metrics,

    callbacks=[PickleCheckpointCallback()]
)

# -----------------------------
# Train
# -----------------------------

trainer.train()


# -----------------------------
# Save Final Model
# -----------------------------

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)


# -----------------------------
# Save Final Pickle
# -----------------------------

final_pickle = os.path.join(
    OUTPUT_DIR,
    "final_model_state.pkl"
)

final_state = {
    "model_state_dict": trainer.model.state_dict(),
    "training_args": training_args
}

with open(final_pickle, "wb") as f:
    pickle.dump(final_state, f)

print(f"\nFinal pickle saved → {final_pickle}")

# -----------------------------
# Evaluate
# -----------------------------

metrics = trainer.evaluate()

print("\nFinal Evaluation Metrics")
print(metrics)

files.download("trained_model.zip")