# -*- coding: utf-8 -*-
"""Final_ImageClassification_Model_Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwg08yY7tSs3ueB_BwHWCgIrykv4JV0F
"""

# !pip install tensorflow typing

"""# Final Training Code"""

from typing import Annotated

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers, models

df = pd.read_pickle(
    "/content/drive/MyDrive/Datasets/Processed/images/images_preprocessed.pkl"
)

X = np.stack(df["image"].values).astype(np.float32)  # (n, 80, 60, 3)
y = df["label"].values

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

unique_labels = np.unique(y_train)
label_mapping = {old: new for new, old in enumerate(sorted(unique_labels))}
y_train = np.array([label_mapping[l] for l in y_train])
y_val = np.array([label_mapping[l] for l in y_val])
y_test = np.array([label_mapping[l] for l in y_test])

num_classes = len(unique_labels)
print(f"Classes: {num_classes}, Mapping: {label_mapping}")

class_names = list(df["masterCategory"].unique())
print(f"Categories: {class_names}")

# Need to understand more about how the layering works for better understading of training future models.

model = models.Sequential(
    [
        layers.Input(shape=(80, 60, 3)),
        layers.Conv2D(16, (3, 3), activation="relu"),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(32, (3, 3), activation="relu"),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(64, (3, 3), activation="relu"),
        layers.MaxPooling2D((2, 2)),
        layers.Flatten(),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.5),
        layers.Dense(num_classes),
    ]
)

model.compile(
    optimizer="adam",
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=18,
    batch_size=32,
    verbose=1,
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Accuracy: {test_acc:.4f}")
print(f"Test Loss: {test_loss:.4f}")

y_pred = np.argmax(model.predict(X_test), axis=1)

plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix(y_test, y_pred),
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names,
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=class_names, zero_division=0))

model.save("/content/drive/MyDrive/Models/image_classifier_ecommerce.keras")

# Save in native Keras format (already have this)
model.save("/content/drive/MyDrive/Models/image_classifier_ecommerce.keras")

# Save model architecture and weights as pickle
import pickle

# Save just the model configuration and weights separately as pickle
model_config = model.get_config()
model_weights = model.get_weights()

model_data = {
    "config": model_config,
    "weights": model_weights,
    "num_classes": num_classes,
    "class_names": class_names,
    "label_mapping": label_mapping,
}

with open("/content/drive/MyDrive/Models/image_classifier_ecommerce.pkl", "wb") as f:
    pickle.dump(model_data, f)

print("Model saved as .keras, and .pkl formats")
